node_js:
- 8

env:
  global:
    - GIT_NAME: dwatow
    - GIT_EMAIL: dwatow@gmail.com
    - GITHUB_REPO:  dwatow/javascript-primer
    - GIT_SOURCE: _docpress

script:
- npm install     # ...or whatever your test command is
- npm audit fix
- npm run build

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages -e; fi